// This file is auto-generated by tauri-specta. Do not edit manually.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openService(payload: ServiceWebviewCommandPayload) : Promise<void> {
    await TAURI_INVOKE("open_service", { payload });
},
async hideAllWebviews() : Promise<void> {
    await TAURI_INVOKE("hide_all_webviews");
},
async setAllServiceWebviewsAudioMuted(payload: AudioMutedPayload) : Promise<void> {
    await TAURI_INVOKE("set_all_service_webviews_audio_muted", { payload });
},
async closeAllServiceWebviews() : Promise<void> {
    await TAURI_INVOKE("close_all_service_webviews");
},
async setRightPanelWidth(payload: RightPanelWidthPayload) : Promise<void> {
    await TAURI_INVOKE("set_right_panel_width", { payload });
},
async saveWorkspaceConfigExport(contents: string, defaultFilename: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_workspace_config_export", { contents, defaultFilename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartApp() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reloadWebview(payload: WebviewIdPayload) : Promise<void> {
    await TAURI_INVOKE("reload_webview", { payload });
},
async reportOutlookBadge(payload: string) : Promise<void> {
    await TAURI_INVOKE("report_outlook_badge", { payload });
},
async reportTeamsBadge(payload: string) : Promise<void> {
    await TAURI_INVOKE("report_teams_badge", { payload });
},
async reportResourceUsage(payload: string) : Promise<void> {
    await TAURI_INVOKE("report_resource_usage", { payload });
},
async closeWebview(payload: WebviewIdPayload) : Promise<void> {
    await TAURI_INVOKE("close_webview", { payload });
},
async deleteWebview(payload: DeleteWebviewPayload) : Promise<void> {
    await TAURI_INVOKE("delete_webview", { payload });
},
async loadService(payload: ServiceWebviewCommandPayload) : Promise<void> {
    await TAURI_INVOKE("load_service", { payload });
},
async showContextMenu(id: string, disabled: boolean) : Promise<void> {
    await TAURI_INVOKE("show_context_menu", { id, disabled });
},
async updateTrayIcon(hasUnread: boolean) : Promise<void> {
    await TAURI_INVOKE("update_tray_icon", { hasUnread });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AudioMutedPayload = { muted: boolean }
export type DeleteWebviewPayload = { id: string; storageKey: string }
export type RightPanelWidthPayload = { width: number }
export type ServiceWebviewCommandPayload = { id: string; url: string; storageKey: string; allowNotifications: boolean; badgeMonitoringEnabled: boolean; spellCheckEnabled: boolean; resourceUsageMonitoringEnabled: boolean }
export type WebviewIdPayload = { id: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
