// This file is auto-generated by tauri-specta. Do not edit manually.
// It is regenerated every time `yarn tauri dev` starts (debug builds only).
// Commit this file so CI and release builds have stable types without running cargo.

import { invoke } from "@tauri-apps/api/core";

// ---------------------------------------------------------------------------
// Payload types (mirror of the #[derive(specta::Type)] structs in Rust)
// ---------------------------------------------------------------------------

export type WebviewIdPayload = {
  id: string;
};

export type DeleteWebviewPayload = {
  id: string;
  storageKey: string;
};

export type RightPanelWidthPayload = {
  width: number;
};

export type ServiceWebviewCommandPayload = {
  id: string;
  url: string;
  storageKey: string;
  allowNotifications: boolean;
  badgeMonitoringEnabled: boolean;
  spellCheckEnabled: boolean;
  resourceUsageMonitoringEnabled: boolean;
};

// ---------------------------------------------------------------------------
// Typed command wrappers
// ---------------------------------------------------------------------------

export const commands = {
  openService: (payload: ServiceWebviewCommandPayload) =>
    invoke<void>("open_service", { payload }),

  loadService: (payload: ServiceWebviewCommandPayload) =>
    invoke<void>("load_service", { payload }),

  hideAllWebviews: () =>
    invoke<void>("hide_all_webviews"),

  closeAllServiceWebviews: () =>
    invoke<void>("close_all_service_webviews"),

  reloadWebview: (payload: WebviewIdPayload) =>
    invoke<void>("reload_webview", { payload }),

  closeWebview: (payload: WebviewIdPayload) =>
    invoke<void>("close_webview", { payload }),

  deleteWebview: (payload: DeleteWebviewPayload) =>
    invoke<void>("delete_webview", { payload }),

  setRightPanelWidth: (payload: RightPanelWidthPayload) =>
    invoke<void>("set_right_panel_width", { payload }),

  saveWorkspaceConfigExport: (contents: string, defaultFilename: string) =>
    invoke<boolean>("save_workspace_config_export", { contents, defaultFilename }),

  restartApp: () =>
    invoke<null>("restart_app"),

  showContextMenu: (id: string, disabled: boolean) =>
    invoke<void>("show_context_menu", { id, disabled }),

  updateTrayIcon: (hasUnread: boolean) =>
    invoke<void>("update_tray_icon", { hasUnread }),

  reportOutlookBadge: (payload: string) =>
    invoke<void>("report_outlook_badge", { payload }),

  reportTeamsBadge: (payload: string) =>
    invoke<void>("report_teams_badge", { payload }),

  reportResourceUsage: (payload: string) =>
    invoke<void>("report_resource_usage", { payload }),
};
