mod badge_payload;
mod app_state;
mod desktop_ui;
mod download_dialog;
mod file_drop;
#[cfg(target_os = "macos")]
mod macos_defaults;
mod navigation_bridge;
mod service_webview_badge_scripts;
mod service_webview_resource_usage;
mod service_webview_runtime_scripts;
mod service_runtime;
mod service_storage;
mod service_webview;
mod webview_commands;
mod window_layout;

use std::sync::atomic::{AtomicU64, Ordering};
use std::time::Duration;
use tauri::Manager;
use tauri_specta::{collect_commands, Builder as SpectaBuilder};

#[cfg(test)]
mod lib_tests;

#[tauri::command]
#[specta::specta]
fn show_context_menu(
    app: tauri::AppHandle,
    window: tauri::Window,
    id: String,
    disabled: bool,
    show_badge: bool,
    affect_tray: bool,
    mute_audio: bool,
) {
    desktop_ui::show_context_menu(app, window, id, disabled, show_badge, affect_tray, mute_audio);
}

#[tauri::command]
#[specta::specta]
fn update_tray_icon(app: tauri::AppHandle, has_unread: bool) {
    desktop_ui::update_tray_icon(app, has_unread);
}

/// Builds the specta command registry.
///
/// Extracted so it can be called from both `run()` and the
/// `tauri_commands_typescript_is_up_to_date` test without duplication.
/// Every Tauri command must appear in this list — `collect_commands!` is the
/// single source of truth for both the invoke handler and the TS export.
pub(crate) fn build_specta() -> SpectaBuilder<tauri::Wry> {
    SpectaBuilder::<tauri::Wry>::new().commands(collect_commands![
        webview_commands::open_service,
        webview_commands::hide_all_webviews,
        webview_commands::set_all_service_webviews_audio_muted,
        webview_commands::set_service_webview_audio_muted,
        webview_commands::close_all_service_webviews,
        webview_commands::set_right_panel_width,
        webview_commands::save_workspace_config_export,
        webview_commands::restart_app,
        webview_commands::reload_webview,
        webview_commands::report_outlook_badge,
        webview_commands::report_teams_badge,
        webview_commands::report_resource_usage,
        webview_commands::close_webview,
        webview_commands::delete_webview,
        webview_commands::load_service,
        show_context_menu,
        update_tray_icon,
    ])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    #[cfg(target_os = "macos")]
    macos_defaults::disable_press_and_hold_key_popup();

    let specta_builder = build_specta();

    // In debug builds, regenerate src/lib/tauri-commands.ts so the TypeScript
    // layer always has up-to-date typed wrappers for every Tauri command.
    #[cfg(debug_assertions)]
    specta_builder
        .export(
            specta_typescript::Typescript::default()
                .header("// This file is auto-generated by tauri-specta. Do not edit manually.\n"),
            "../src/lib/tauri-commands.ts",
        )
        .expect("Failed to export TypeScript bindings");

    #[allow(unused_mut)]
    let mut builder = tauri::Builder::default()
        .invoke_handler(specta_builder.invoke_handler())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .manage(app_state::ActiveWebview(std::sync::Mutex::new(String::new())))
        .manage(app_state::ActiveResourceUsageMonitoring(std::sync::Mutex::new(
            false,
        )))
        .manage(app_state::BadgeMonitoringPrefs(std::sync::Mutex::new(
            std::collections::HashMap::new(),
        )))
        .manage(app_state::RightPanelWidth(std::sync::Mutex::new(0.0)))
        .manage(app_state::ServiceAudioMuted(std::sync::Mutex::new(false)))
        .manage(app_state::MainWindowResizeGen(AtomicU64::new(0)));

    #[cfg(feature = "devtools")]
    {
        builder = builder.plugin(tauri_plugin_mcp_bridge::init());
    }

    builder
        .setup(|app| {
            use tauri::menu::{Menu, MenuItem};
            use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
            use tauri::Emitter;

            let app_handle = app.handle().clone();

            app.on_menu_event(move |_app, event| {
                let action_id = event.id.as_ref();
                let _ = app_handle.emit("menu-action", action_id);
            });

            let toggle_i =
                MenuItem::with_id(app, "toggle_window", "Show / Hide Ferx", true, None::<&str>)?;
            let quit_i = MenuItem::with_id(app, "quit_app", "Quit Ferx", true, None::<&str>)?;
            let tray_menu = Menu::with_items(app, &[&toggle_i, &quit_i])?;

            let _tray = TrayIconBuilder::with_id("ferx_tray")
                .menu(&tray_menu)
                .show_menu_on_left_click(false)
                .icon(desktop_ui::tray_icon(false))
                .on_menu_event(|app, event| match event.id.as_ref() {
                    "quit_app" => {
                        app.exit(0);
                    }
                    "toggle_window" => {
                        desktop_ui::toggle_main_window_visibility(app);
                    }
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        let app = tray.app_handle();
                        desktop_ui::toggle_main_window_visibility(app);
                    }
                })
                .build(app)?;

            Ok(())
        })
        .on_window_event(|window, event| match event {
            tauri::WindowEvent::Resized(_) => {
                let debounce = window.state::<app_state::MainWindowResizeGen>();
                let my_gen = debounce.0.fetch_add(1, Ordering::SeqCst) + 1;
                let app = window.app_handle().clone();
                let window_label = window.label().to_string();
                tauri::async_runtime::spawn(async move {
                    tokio::time::sleep(Duration::from_millis(window_layout::RESIZE_DEBOUNCE_MS))
                        .await;
                    let debounce = app.state::<app_state::MainWindowResizeGen>();
                    if debounce.0.load(Ordering::SeqCst) != my_gen {
                        return;
                    }
                    let Some(w) = app.get_window(&window_label) else {
                        return;
                    };
                    let physical_size = w.inner_size().unwrap_or_default();
                    window_layout::apply_active_child_webview_bounds(&w, physical_size);
                });
            }
            tauri::WindowEvent::CloseRequested { api, .. } => {
                api.prevent_close();
                let _ = window.hide();
            }
            _ => {}
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
